export type Post = {
  slug: string;
  title: string;
  date: string;
  category: string;
  excerpt: string;
  type: 'blog' | 'case-study';
  location?: string;
  tags?: string[];
  readingTime?: string;
};

export const allPosts: Post[] = [
  // ── BLOG POSTS ──────────────────────────────────────────────────────────────

  // ── Product Education / Buyer Questions ─────────────────────────────────────
  {
    slug: 'transparent-gas-cylinder-benefits-see-lpg-level-pakistan',
    title: 'Transparent Gas Cylinder Benefits: See Your LPG Level Anytime — The WAA Technologies Advantage',
    date: 'Jul 10, 2026',
    category: 'WAATechCylinders',
    type: 'blog',
    readingTime: '10 min read',
    tags: ['transparent-gas-cylinder-pakistan', 'composite-lpg-cylinders', 'lpg-level-check-pakistan', 'waa-technologies', 'gas-cylinder-features-pakistan', 'fiber-gas-cylinder-pakistan'],
    excerpt: 'Steel LPG cylinders are completely opaque — you have no idea how much gas remains until you run out mid-cooking. WAA Technologies composite cylinders have a translucent HDPE body that lets you see the LPG level at a glance, like a water bottle. This single feature alone changes how Pakistani households and businesses manage their gas supply.',
  },
  {
    slug: 'composite-cylinders-reduce-lifting-injuries-restaurants-pakistan',
    title: 'How Composite LPG Cylinders Reduce Lifting Injuries in Pakistani Restaurant Kitchens',
    date: 'Jul 10, 2026',
    category: 'WAATechCylinders',
    type: 'blog',
    readingTime: '11 min read',
    tags: ['restaurant-gas-cylinder-pakistan', 'composite-lpg-cylinders', 'kitchen-safety-pakistan', 'lpg-cylinder-weight', 'waa-technologies', 'commercial-lpg-pakistan'],
    excerpt: 'A filled steel LPG cylinder weighs 30+ kg. Pakistani restaurant staff lift these multiple times per shift, every day. Back injuries, shoulder strains, and drop accidents are a direct consequence. Composite cylinders weigh 40% less and change the risk profile of every cylinder change in your kitchen.',
  },
  {
    slug: 'composite-lpg-cylinders-food-trucks-street-vendors-pakistan',
    title: 'Composite LPG Cylinders for Food Trucks & Street Vendors in Pakistan — The Complete Guide',
    date: 'Jul 9, 2026',
    category: 'WAATechCylinders',
    type: 'blog',
    readingTime: '12 min read',
    tags: ['food-truck-lpg-pakistan', 'composite-lpg-cylinders', 'street-vendor-gas-cylinder', 'commercial-lpg-pakistan', 'waa-technologies', 'fiber-gas-cylinder-pakistan'],
    excerpt: 'Pakistan\'s food truck and street vendor sector runs on LPG — and conventional steel cylinders create real operational problems: too heavy to move, too opaque to monitor, and too dangerous for crowded public spaces. Composite cylinders solve every one of these problems.',
  },
  {
    slug: 'are-composite-lpg-cylinders-safe-pakistan',
    title: 'Are Composite LPG Cylinders Safe? The Complete Guide for Pakistani Households',
    date: 'Jul 9, 2026',
    category: 'WAATechCylinders',
    type: 'blog',
    readingTime: '11 min read',
    tags: ['composite-lpg-cylinders', 'gas-cylinder-safety-pakistan', 'fiber-gas-cylinder-pakistan', 'lpg-safety', 'waa-technologies', 'iso-certified-cylinder'],
    excerpt: 'Are composite LPG cylinders safe? This is the most-searched question before purchase. The complete answer: yes — and they are measurably safer than steel. Here is every safety question answered with evidence.',
  },
  {
    slug: 'how-to-check-gas-level-composite-cylinder',
    title: 'How to Check Gas Level in a Composite Cylinder Without Lifting It',
    date: 'Jul 9, 2026',
    category: 'WAATechCylinders',
    type: 'blog',
    readingTime: '8 min read',
    tags: ['composite-lpg-cylinders', 'gas-cylinder-level-check', 'fiber-gas-cylinder-pakistan', 'lpg-cylinder-tips', 'waa-technologies'],
    excerpt: 'Checking the gas level in a steel cylinder requires lifting and guessing. WAA Technologies composite cylinders have a translucent body — you can see the LPG level directly, like reading a water bottle. Here is exactly how it works.',
  },

  // ── Safety / News / Regulatory (Batch 1) ────────────────────────────────────
  {
    slug: 'gas-cylinder-blast-incidents-pakistan-2025',
    title: 'Gas Cylinder Blast Incidents in Pakistan 2024–2025: Causes, Statistics, and How to Stay Safe',
    date: 'Jun 24, 2026',
    category: 'WAATechCylinders',
    type: 'blog',
    readingTime: '8 min read',
    tags: ['gas-cylinder-blast-pakistan', 'lpg-explosion-pakistan', 'gas-cylinder-safety-pakistan', 'composite-lpg-cylinders'],
    excerpt: 'Pakistan records hundreds of gas cylinder blast incidents every year. This detailed report covers the 2024–2025 data, root causes, the districts most affected, and the single switch that eliminates explosion risk permanently.',
  },
  {
    slug: 'ogra-rules-lpg-cylinders-pakistan',
    title: 'OGRA Rules for LPG Cylinders in Pakistan — What Every Household and Business Must Know in 2025',
    date: 'Jun 24, 2026',
    category: 'WAATechCylinders',
    type: 'blog',
    readingTime: '9 min read',
    tags: ['ogra-lpg-regulations-pakistan', 'lpg-cylinder-certification-pakistan', 'gas-cylinder-safety-rules', 'composite-lpg-cylinders'],
    excerpt: 'OGRA regulates every LPG cylinder sold and used in Pakistan. Most households and even many businesses are unaware of what is legal, what is not, and what an inspector will check. This guide covers the complete OGRA LPG cylinder rulebook in plain language.',
  },
  {
    slug: 'steel-vs-composite-lpg-cylinder-pakistan',
    title: 'Steel vs Composite LPG Cylinder: Complete Comparison for Pakistani Homes (2025)',
    date: 'Jun 24, 2026',
    category: 'WAATechCylinders',
    type: 'blog',
    readingTime: '10 min read',
    tags: ['steel-vs-composite-lpg-cylinder', 'lpg-cylinder-comparison-pakistan', 'fiber-gas-cylinder-pakistan', 'composite-lpg-cylinders'],
    excerpt: 'Steel or composite? Pakistani households buying a new LPG cylinder face this choice. This side-by-side comparison covers safety, cost, weight, lifespan, gas level visibility, corrosion, and total value over 10 years — with a clear verdict.',
  },
  // ── Safety (Batch 2) ─────────────────────────────────────────────────────────
  {
    slug: 'why-lpg-cylinders-explode-pakistan-how-to-prevent',
    title: 'Why LPG Cylinders Explode in Pakistan — The Science Explained and How to Prevent It',
    date: 'Jun 24, 2026',
    category: 'WAATechCylinders',
    type: 'blog',
    readingTime: '7 min read',
    tags: ['lpg-cylinder-explosion-causes', 'gas-cylinder-blast-prevention', 'non-blast-cylinder-pakistan', 'composite-lpg-cylinders'],
    excerpt: 'Understanding why LPG cylinders explode — BLEVE physics, valve failures, corrosion, overfilling — is the first step to preventing it. This guide explains the science in plain Urdu-context language and shows why composite cylinders physically cannot explode.',
  },
  {
    slug: 'psi-certified-gas-cylinder-pakistan',
    title: 'PSI Certified Gas Cylinder in Pakistan — What the Certification Means and Why It Matters',
    date: 'Jun 24, 2026',
    category: 'WAATechCylinders',
    type: 'blog',
    readingTime: '6 min read',
    tags: ['psi-certified-gas-cylinder-pakistan', 'lpg-cylinder-certification', 'gas-cylinder-safety-standards', 'composite-lpg-cylinders'],
    excerpt: 'PSI, ISO, OGRA, EN — LPG cylinder certifications in Pakistan can be confusing. This guide explains exactly what PSI certification means, which Pakistani standard it corresponds to, what an ISO 11119-3 and EN 14427 certification covers, and how to verify a cylinder is genuinely certified.',
  },
  {
    slug: 'gas-cylinder-warning-signs-pakistan',
    title: 'Is Your Gas Cylinder Safe? 5 Warning Signs Pakistani Families Must Never Ignore',
    date: 'Jun 24, 2026',
    category: 'WAATechCylinders',
    type: 'blog',
    readingTime: '6 min read',
    tags: ['gas-cylinder-safety-warning-signs', 'lpg-cylinder-danger-signs', 'gas-leak-detection-pakistan', 'composite-lpg-cylinders'],
    excerpt: '5 specific warning signs that your LPG cylinder or connection is dangerously unsafe — each explained with what to look for, what it means, and the exact steps to take immediately. Includes the most-ignored sign that causes most Pakistani kitchen fires.',
  },
  // ── Price / Buy (Batch 3) ────────────────────────────────────────────────────
  {
    slug: 'composite-lpg-cylinder-price-pakistan-2025',
    title: 'Composite LPG Cylinder Price in Pakistan 2025 — How Much Does a Fiber Gas Cylinder Cost?',
    date: 'Jun 24, 2026',
    category: 'WAATechCylinders',
    type: 'blog',
    readingTime: '7 min read',
    tags: ['composite-lpg-cylinder-price-pakistan', 'fiber-gas-cylinder-price', 'lpg-cylinder-cost-pakistan', 'buy-composite-cylinder-pakistan'],
    excerpt: 'Complete 2025 price guide for composite LPG cylinders in Pakistan — 5 kg, 10 kg, and 12 kg sizes. Includes price comparison with steel cylinders, total cost of ownership over 5 years, where to buy, and which size is right for your household.',
  },
  // ── Comparison (Batch 4) ─────────────────────────────────────────────────────
  {
    slug: 'parco-vs-waa-technologies-cylinder-pakistan',
    title: 'PARCO vs WAA Technologies LPG Cylinder — Which Is the Better Choice for Pakistan?',
    date: 'Jun 24, 2026',
    category: 'WAATechCylinders',
    type: 'blog',
    readingTime: '8 min read',
    tags: ['parco-lpg-cylinder-pakistan', 'waa-technologies-cylinder', 'lpg-cylinder-brands-pakistan', 'composite-lpg-cylinders'],
    excerpt: 'PARCO and WAA Technologies are two prominent names in Pakistan\'s LPG cylinder market. This honest comparison covers cylinder type, safety certification, price, weight, gas level visibility, dealer network, and after-sales support — so you can decide which is right for your home.',
  },
  {
    slug: 'chinese-imported-vs-pakistani-composite-lpg-cylinder',
    title: 'Chinese Imported LPG Cylinder vs Pakistani Composite Cylinder — An Honest Comparison',
    date: 'Jun 24, 2026',
    category: 'WAATechCylinders',
    type: 'blog',
    readingTime: '7 min read',
    tags: ['chinese-lpg-cylinder-pakistan', 'imported-vs-local-composite-cylinder', 'lpg-cylinder-quality-pakistan', 'composite-lpg-cylinders'],
    excerpt: 'Pakistani markets are flooded with cheap imported cylinders from China. This comparison examines certification standards, material quality, safety testing, pricing, and long-term reliability — and explains why locally manufactured composite cylinders are the safer, smarter choice.',
  },
  {
    slug: 'traditional-steel-gola-vs-fiber-lpg-cylinder-cost-pakistan',
    title: 'Traditional Steel Gola vs Fiber LPG Cylinder — Complete Cost Comparison Over 5 Years in Pakistan',
    date: 'Jun 24, 2026',
    category: 'WAATechCylinders',
    type: 'blog',
    readingTime: '7 min read',
    tags: ['steel-gola-vs-fiber-cylinder-pakistan', 'lpg-cylinder-cost-comparison', 'composite-cylinder-value-pakistan', 'buy-composite-cylinder-pakistan'],
    excerpt: 'The traditional steel "gola" costs less upfront — but over 5 years, the composite fiber cylinder wins decisively on total cost. This detailed cost breakdown shows the real numbers for Pakistani households at current LPG prices.',
  },
  // ── City Pages (Batch 5) ─────────────────────────────────────────────────────
  {
    slug: 'composite-lpg-cylinder-lahore',
    title: 'Composite LPG Cylinder in Lahore — Buy, Refill, and Authorised Dealers Near You',
    date: 'Jun 24, 2026',
    category: 'WAATechCylinders',
    type: 'blog',
    readingTime: '7 min read',
    tags: ['composite-lpg-cylinder-lahore', 'fiber-gas-cylinder-lahore', 'lpg-cylinder-dealer-lahore', 'buy-lpg-cylinder-lahore'],
    excerpt: 'Complete guide to buying and refilling a composite LPG cylinder in Lahore — WAA Technologies authorised dealers across DHA, Gulberg, Bahria Town, Johar Town, Model Town, and all major Lahore districts. Includes pricing, delivery options, and safety tips for Lahore households.',
  },
  {
    slug: 'composite-lpg-cylinder-karachi',
    title: 'Composite LPG Cylinder in Karachi — Buy, Refill, and Authorised Dealers Near You',
    date: 'Jun 24, 2026',
    category: 'WAATechCylinders',
    type: 'blog',
    readingTime: '7 min read',
    tags: ['composite-lpg-cylinder-karachi', 'fiber-gas-cylinder-karachi', 'lpg-cylinder-dealer-karachi', 'buy-lpg-cylinder-karachi'],
    excerpt: 'Complete guide to buying and refilling a composite LPG cylinder in Karachi — WAA Technologies authorised dealers across Defence, Clifton, Gulshan, PECHS, North Karachi, and all major Karachi districts. Includes coastal corrosion advantages, pricing, and delivery options.',
  },
  {
    slug: 'composite-lpg-cylinder-islamabad',
    title: 'Composite LPG Cylinder in Islamabad and Rawalpindi — Buy, Refill, and Authorised Dealers',
    date: 'Jun 24, 2026',
    category: 'WAATechCylinders',
    type: 'blog',
    readingTime: '7 min read',
    tags: ['composite-lpg-cylinder-islamabad', 'fiber-gas-cylinder-rawalpindi', 'lpg-cylinder-dealer-islamabad', 'buy-lpg-cylinder-islamabad'],
    excerpt: 'Complete guide to buying and refilling a composite LPG cylinder in Islamabad and Rawalpindi — WAA Technologies authorised dealers across F-6, F-7, F-10, G-11, Bahria Town, and DHA. Includes winter gas shortage preparedness tips for twin cities households.',
  },
  // ── Authority / Industry (Batch 6) ───────────────────────────────────────────
  {
    slug: 'lpg-industry-pakistan-market-size-future-outlook',
    title: 'LPG Industry in Pakistan: Market Size, Key Players, and Future Outlook (2025)',
    date: 'Jun 24, 2026',
    category: 'WAATechCylinders',
    type: 'blog',
    readingTime: '10 min read',
    tags: ['lpg-industry-pakistan', 'pakistan-lpg-market-size', 'lpg-cylinder-manufacturers-pakistan', 'composite-lpg-cylinders'],
    excerpt: 'Pakistan\'s LPG industry is a PKR 600+ billion market serving 10 million households. This 2025 industry overview covers market size, growth drivers, key manufacturers, OGRA\'s role, the shift from steel to composite cylinders, and the investment opportunity in Pakistan\'s LPG transition.',
  },
  {
    slug: 'how-lpg-cylinders-tested-safety-pakistan',
    title: 'How LPG Cylinders Are Tested for Safety in Pakistan — The Complete Certification Process',
    date: 'Jun 24, 2026',
    category: 'WAATechCylinders',
    type: 'blog',
    readingTime: '8 min read',
    tags: ['lpg-cylinder-safety-testing-pakistan', 'cylinder-certification-process', 'iso-11119-3-testing', 'composite-lpg-cylinders'],
    excerpt: 'Before an LPG cylinder reaches your kitchen, it undergoes rigorous safety testing. This guide explains the complete certification process — burst testing, cycle testing, UV testing, drop testing — and what ISO 11119-3 and EN 14427-2022 certification actually certifies.',
  },
  {
    slug: 'ogra-licensed-lpg-cylinder-manufacturers-pakistan',
    title: 'OGRA Licensed LPG Cylinder Manufacturers in Pakistan — Complete 2025 List',
    date: 'Jun 24, 2026',
    category: 'WAATechCylinders',
    type: 'blog',
    readingTime: '8 min read',
    tags: ['ogra-licensed-lpg-manufacturers-pakistan', 'lpg-cylinder-brands-pakistan', 'certified-gas-cylinders-pakistan', 'waa-technologies'],
    excerpt: 'Only OGRA-licensed manufacturers can legally sell LPG cylinders in Pakistan. This guide lists the licensed manufacturers, explains the licensing requirements, and shows how to verify whether a cylinder brand is genuinely OGRA-approved before you buy.',
  },
  {
    slug: 'pakistan-lpg-imports-vs-domestic-production-2025',
    title: 'Pakistan LPG Imports vs Domestic Production — 2025 Data and What It Means for Cylinder Prices',
    date: 'Jun 24, 2026',
    category: 'WAATechCylinders',
    type: 'blog',
    readingTime: '9 min read',
    tags: ['pakistan-lpg-imports-2025', 'pakistan-lpg-production', 'lpg-price-pakistan-2025', 'lpg-supply-chain-pakistan'],
    excerpt: 'Pakistan imports over 60% of its LPG. This 2025 analysis covers import volumes, key suppliers (Saudi Arabia, UAE, Iraq), domestic production from OGDCL and PPL, the import-export price mechanism, and how supply-demand dynamics translate into the cylinder prices Pakistani households pay.',
  },
  // ── Existing new articles ─────────────────────────────────────────────────────
  {
    slug: 'why-restaurants-switching-composite-lpg-cylinders-pakistan',
    title: 'Why Pakistani Restaurants Are Switching to Composite LPG Cylinders — The Complete Business Case',
    date: 'Jun 21, 2026',
    category: 'WAATechCylinders',
    type: 'blog',
    readingTime: '11 min read',
    tags: ['composite-lpg-cylinders-restaurants', 'restaurant-lpg-pakistan', 'commercial-gas-cylinders-pakistan', 'fiber-lpg-cylinders'],
    excerpt: 'From Lahore\'s Food Street to Karachi\'s Boat Basin, Pakistan\'s restaurant industry is rapidly replacing steel LPG cylinders with composite alternatives. Here is the complete business case — safety, cost, operations, and compliance — driving the switch.',
  },
  {
    slug: 'how-to-safely-connect-lpg-cylinder-regulator-at-home',
    title: 'How to Safely Connect an LPG Cylinder Regulator at Home — Step-by-Step Guide for Pakistan',
    date: 'Jun 21, 2026',
    category: 'WAATechCylinders',
    type: 'blog',
    readingTime: '9 min read',
    tags: ['lpg-regulator-connection', 'gas-cylinder-regulator-pakistan', 'lpg-cylinder-safety', 'composite-lpg-cylinders'],
    excerpt: 'Fitting an LPG cylinder regulator incorrectly is one of the most common causes of gas leaks in Pakistani homes. This complete step-by-step guide shows you exactly how to connect a regulator safely — including the checks most households skip.',
  },
  {
    slug: '8-crucial-gas-cylinder-safety-rules-every-household-must-follow',
    title: '8 Crucial Gas Cylinder Safety Rules Every Pakistani Household Must Follow',
    date: 'Jun 21, 2026',
    category: 'WAATechCylinders',
    type: 'blog',
    readingTime: '9 min read',
    tags: ['gas-cylinder-safety-rules', 'lpg-safety-pakistan', 'household-gas-safety', 'composite-lpg-cylinders'],
    excerpt: 'Gas cylinder accidents claim lives and destroy homes across Pakistan every year — and almost every one is preventable. These 8 essential safety rules cover storage, handling, leak detection, emergency response, and cylinder choice for every Pakistani household.',
  },
  {
    slug: 'lpg-gas-shortage-pakistan-composite-cylinders-solution',
    title: 'LPG Gas Shortage in Pakistan: Why Composite Cylinders Are the Solution',
    date: 'Jun 21, 2026',
    category: 'WAATechCylinders',
    type: 'blog',
    readingTime: '11 min read',
    tags: ['lpg-shortage-pakistan', 'composite-cylinders-solution', 'lpg-gas-shortage', 'fiber-lpg-cylinders'],
    excerpt: 'Pakistan faces recurring LPG shortages driven by supply chain bottlenecks and ageing infrastructure. Composite cylinders — lighter, more durable, and stackable — are a practical part of the solution every household can adopt today.',
  },
  {
    slug: 'winter-gas-shortage-pakistan-2025-prepare-your-home',
    title: 'Winter Gas Shortage Pakistan 2025 — Prepare Your Home',
    date: 'Jun 21, 2026',
    category: 'WAATechCylinders',
    type: 'blog',
    readingTime: '12 min read',
    tags: ['winter-gas-shortage-pakistan', 'winter-heating-lpg', 'home-gas-preparation', 'composite-lpg-cylinders'],
    excerpt: 'Every winter, millions of Pakistani households face acute gas shortages. Here is how to prepare your home before the cold hits — and why an LPG composite cylinder is the most reliable backup you can have.',
  },
  {
    slug: 'ramadan-gas-safety-tips-pakistani-kitchens',
    title: 'Ramadan Gas Safety Tips for Pakistani Kitchens',
    date: 'Jun 21, 2026',
    category: 'WAATechCylinders',
    type: 'blog',
    readingTime: '13 min read',
    tags: ['ramadan-gas-safety', 'kitchen-gas-safety-pakistan', 'ramadan-cooking', 'safe-lpg-cylinders'],
    excerpt: 'Sehri and Iftar cooking marathons significantly increase kitchen gas usage during Ramadan. Follow these essential LPG safety tips — and understand why a composite cylinder makes every Pakistani kitchen safer this holy month.',
  },
  {
    slug: 'load-shedding-lpg-pakistanis-switching-gas-cooking',
    title: 'Load Shedding and LPG: Why More Pakistanis Are Switching to Gas Cooking',
    date: 'Jun 21, 2026',
    category: 'WAATechCylinders',
    type: 'blog',
    readingTime: '12 min read',
    tags: ['load-shedding-lpg', 'gas-cooking-pakistan', 'lpg-alternative-electricity', 'composite-lpg-cylinders'],
    excerpt: 'With electricity load shedding stretching 10–14 hours in parts of Pakistan, LPG-powered cooking has become the practical choice for millions of households. Here is why composite cylinders are the smartest way to make the switch.',
  },
  {
    slug: 'cost-benefits-of-composite-lpg-cylinders-a-smart-investment-for-2025',
    title: 'Cost Benefits of Composite LPG Cylinders: A Smart Investment for 2025',
    date: 'May 2, 2025',
    category: 'WAATechCylinders',
    type: 'blog',
    tags: ['composite-cylinder-savings', 'cost-effective-composite-lpg-cylinders', 'long-life-lpg-cylinders'],
    excerpt: 'Composite LPG cylinders may have a higher upfront cost than steel, but their 20+ year lifespan, zero maintenance, and safety benefits make them the smarter long-term investment for Pakistani households.',
  },
  {
    slug: 'the-science-of-assisting-with-leak-proof-fiber-lpg-cylinders',
    title: 'The Science of Assisting with Leak-Proof Fiber LPG Cylinders',
    date: 'Feb 11, 2025',
    category: 'WAATechCylinders',
    type: 'blog',
    tags: ['leak-proof-gas-cylinders', 'fiber-lpg-cylinders'],
    excerpt: 'Exploring the engineering principles behind WAA\'s jointless composite design and how it virtually eliminates gas leakage compared to traditional welded steel cylinders.',
  },
  {
    slug: 'how-lightweight-lpg-cylinders-are-affecting-the-sector',
    title: 'How Lightweight LPG Cylinders Are Affecting the Sector',
    date: 'Feb 11, 2025',
    category: 'WAATechCylinders',
    type: 'blog',
    tags: ['lightweight-gas-cylinders', 'fiber-lpg-cylinders'],
    excerpt: 'The shift from heavy steel to lightweight composite cylinders is reshaping Pakistan\'s LPG distribution sector — from transport logistics to retail convenience.',
  },
  {
    slug: 'environmentally-friendly-gas-cylinder-toward-sustainable-energy-storage-as-knowledge-of-environmental-consequences-spreads-around-the-globe',
    title: 'Environmentally Friendly Gas Cylinder: Toward Sustainable Energy Storage',
    date: 'Feb 10, 2025',
    category: 'WAATechCylinders',
    type: 'blog',
    tags: ['eco-friendly-lpg-cylinders', 'sustainable-lpg-cylinders'],
    excerpt: 'As environmental consciousness grows globally, composite cylinders emerge as the sustainable alternative — using 70% less material and lasting twice as long as steel.',
  },
  {
    slug: 'smart-lpg-cylinders-iot-improves-efficiency-and-safety',
    title: 'Smart LPG Cylinders: IoT Improves Efficiency and Safety',
    date: 'Feb 10, 2025',
    category: 'WAATechCylinders',
    type: 'blog',
    tags: ['fiber-lpg-cylinders', 'safe-lpg-cylinders'],
    excerpt: 'The next frontier for LPG safety: how IoT sensors and smart monitoring are being integrated with composite cylinder designs to deliver real-time usage data.',
  },
  {
    slug: 'the-future-of-lpg-the-reason-fiber-cylinders-are-substituting-steel',
    title: 'The Future of LPG: The Reason Fiber Cylinders Are Substituting Steel',
    date: 'Feb 10, 2025',
    category: 'WAATechCylinders',
    type: 'blog',
    tags: ['fiber-lpg-cylinders', 'lightweight-gas-cylinders'],
    excerpt: 'Steel LPG cylinders dominated for decades, but composite fiber technology is now rapidly replacing them globally. Here\'s the technical and economic case for the transition.',
  },
  {
    slug: 'the-transformation-of-energy-storage-via-fiber-lpg-cylinders',
    title: 'The Transformation of Energy Storage via Fiber LPG Cylinders',
    date: 'Feb 10, 2025',
    category: 'WAATechCylinders',
    type: 'blog',
    tags: ['fiber-lpg-cylinders', 'sustainable-lpg-cylinders'],
    excerpt: 'Fiber composite cylinders are not just safer — they represent a fundamental transformation in how households and businesses store and use portable energy.',
  },
  {
    slug: 'eco-friendly-gas-cylinder',
    title: 'Eco Friendly Gas Cylinder: The Future of Sustainable Energy Storage',
    date: 'Feb 9, 2025',
    category: 'WAATechCylinders',
    type: 'blog',
    tags: ['eco-friendly-gas-cylinder', 'sustainable-lpg-cylinders'],
    excerpt: 'Composite cylinders reduce manufacturing emissions, use less material, and last longer — making them the most eco-friendly LPG storage solution available today.',
  },
  {
    slug: 'the-science-supporting-leak-proof-fiber-lpg-cylinders',
    title: 'The Science Supporting Leak-Proof Fiber LPG Cylinders',
    date: 'Feb 7, 2025',
    category: 'WAATechCylinders',
    type: 'blog',
    tags: ['leak-proof-gas-cylinders', 'fiber-lpg-cylinders'],
    excerpt: 'A deep dive into the materials science and manufacturing processes that make WAA composite cylinders inherently more leak-resistant than traditional steel alternatives.',
  },
  {
    slug: 'technologies-driving-the-change-from-steel-to-fiber-lpg-cylinders',
    title: 'Technologies Driving the Change from Steel to Fiber LPG Cylinders',
    date: 'Feb 7, 2025',
    category: 'WAATechCylinders',
    type: 'blog',
    tags: ['fiber-lpg-cylinders', 'sustainable-lpg-cylinders'],
    excerpt: 'CNC filament winding, HDPE liners, and advanced resin systems — the key manufacturing technologies enabling the global transition to composite LPG cylinders.',
  },
  {
    slug: 'novel-ideas-guiding-the-transition-from-steel-to-fiber-lpg-cylinders',
    title: 'Novel Ideas Guiding the Transition from Steel to Fiber LPG Cylinders',
    date: 'Jan 28, 2025',
    category: 'WAATechCylinders',
    type: 'blog',
    tags: ['fiber-lpg-cylinders'],
    excerpt: 'Innovative engineering concepts driving the global shift from conventional steel gas cylinders to advanced composite fiber alternatives.',
  },
  {
    slug: 'fiber-gas-cylinders-support-a-sustainable-future',
    title: 'Fiber Gas Cylinders Support a Sustainable Future',
    date: 'Jan 25, 2025',
    category: 'WAATechCylinders',
    type: 'blog',
    tags: ['eco-friendly-lpg-cylinders', 'sustainable-lpg-cylinders'],
    excerpt: 'How fiber composite gas cylinders are contributing to a more sustainable energy future — for Pakistan and the world.',
  },
  {
    slug: 'the-environmental-advantages-of-changing-to-fiber-lpg-cylinders',
    title: 'The Environmental Advantages of Changing to Fiber LPG Cylinders',
    date: 'Jan 22, 2025',
    category: 'WAATechCylinders',
    type: 'blog',
    tags: ['eco-friendly-lpg-cylinders', 'recyclable-gas-cylinders'],
    excerpt: 'Switching to fiber LPG cylinders offers significant environmental benefits — less raw material, lower carbon footprint, and a longer service life.',
  },
  {
    slug: 'the-top-10-applications-for-lpg-fiber-cylinders-in-industries-and-homes',
    title: 'The Top 10 Applications for LPG Fiber Cylinders in Industries and Homes',
    date: 'Jan 18, 2025',
    category: 'WAATechCylinders',
    type: 'blog',
    tags: ['fiber-lpg-cylinders', 'lightweight-gas-cylinders'],
    excerpt: 'From residential kitchens to industrial heating, discover the top 10 practical applications where composite LPG cylinders outperform steel.',
  },
  {
    slug: 'the-reasons-fiber-cylinders-are-ideal-for-barbecuing-and-outdoor-events',
    title: 'The Reasons Fiber Cylinders Are Ideal for Barbecuing and Outdoor Events',
    date: 'Jan 15, 2025',
    category: 'WAATechCylinders',
    type: 'blog',
    tags: ['lightweight-gas-cylinders', 'safe-lpg-cylinders'],
    excerpt: 'Lightweight, portable, and UV-resistant — composite LPG cylinders are the perfect choice for BBQs, outdoor kitchens, and events.',
  },
  {
    slug: 'lpg-fiber-cylinder-applications-in-the-automobile-sector',
    title: 'LPG Fiber Cylinder Applications in the Automobile Sector',
    date: 'Jan 12, 2025',
    category: 'WAATechCylinders',
    type: 'blog',
    tags: ['fiber-lpg-cylinders', 'hdpe-lpg-cylinders'],
    excerpt: 'Composite LPG cylinders are finding increasing use in automotive and transport applications where weight reduction and safety are paramount.',
  },
  {
    slug: 'fiber-lpg-cylinders-advantages-for-the-environment',
    title: 'Fiber LPG Cylinders Advantages for the Environment',
    date: 'Jan 10, 2025',
    category: 'WAATechCylinders',
    type: 'blog',
    tags: ['eco-friendly-lpg-cylinders', 'recyclable-gas-cylinders'],
    excerpt: 'An in-depth look at how fiber LPG cylinders deliver measurable environmental advantages over conventional steel alternatives.',
  },
  {
    slug: 'how-eco-friendly-lpg-fiber-cylinders-are-reducing-carbon-footprint-globally',
    title: 'How Eco-Friendly LPG Fiber Cylinders Are Reducing Carbon Footprint Globally',
    date: 'Jan 8, 2025',
    category: 'WAATechCylinders',
    type: 'blog',
    tags: ['eco-friendly-lpg-cylinders', 'sustainable-lpg-cylinders', 'low-carbon-gas-cylinders'],
    excerpt: 'Global data on how switching to composite LPG cylinders is reducing carbon emissions across residential and commercial sectors.',
  },
  {
    slug: 'eco-friendly-lpg-fiber-cylinders-reducing-carbon',
    title: 'Eco-Friendly LPG Fiber Cylinders: Reducing Carbon Emissions',
    date: 'Jan 6, 2025',
    category: 'WAATechCylinders',
    type: 'blog',
    tags: ['eco-friendly-lpg-cylinders', 'low-carbon-gas-cylinders'],
    excerpt: 'How composite fiber cylinders contribute to measurable carbon emission reductions in Pakistan\'s LPG sector.',
  },
  {
    slug: 'how-fiber-cylinders-help-meet-industrial-and-construction-needs',
    title: 'How Fiber Cylinders Help Meet Industrial and Construction Needs',
    date: 'Jan 4, 2025',
    category: 'WAATechCylinders',
    type: 'blog',
    tags: ['fiber-lpg-cylinders', 'lightweight-gas-cylinders'],
    excerpt: 'Industrial and construction sites demand robust, safe, and portable energy solutions — composite fiber cylinders deliver on all three counts.',
  },
  {
    slug: 'composite-lpg-cylinders-over-traditional-metal-cylinders',
    title: 'Composite LPG Cylinders Over Traditional Metal Cylinders',
    date: 'Dec 28, 2024',
    category: 'WAATechCylinders',
    type: 'blog',
    tags: ['composite-lpg-cylinders', 'composite-vs-metal-lpg'],
    excerpt: 'A comprehensive comparison of composite and metal LPG cylinders — safety, weight, lifespan, cost, and environmental impact.',
  },
  {
    slug: 'winter-heating',
    title: 'LPG Composite Cylinders for Winter Heating',
    date: 'Dec 20, 2024',
    category: 'WAATechCylinders',
    type: 'blog',
    tags: ['winter-heating-solutions', 'safe-lpg-cylinders', 'explosion-proof-lpg-cylinders'],
    excerpt: 'As temperatures drop across Pakistan, WAA composite cylinders provide the safest and most reliable LPG solution for home and office winter heating.',
  },
  {
    slug: 'the-future-of-lpg-cylinders',
    title: 'The Future of LPG Cylinders',
    date: 'Dec 15, 2024',
    category: 'WAATechCylinders',
    type: 'blog',
    tags: ['safer-lpg-cylinders', 'recyclable-lpg-cylinders', 'jointless-lpg-cylinders'],
    excerpt: 'Where is the global LPG cylinder market headed? Composite materials, smart monitoring, and sustainability are shaping the next generation of gas storage.',
  },
  {
    slug: 'fiber-gas-cylinders-in-marine-applications-safety-and-durability-advantages',
    title: 'Fiber Gas Cylinders in Marine Applications: Safety and Durability Advantages',
    date: 'Dec 10, 2024',
    category: 'WAATechCylinders',
    type: 'blog',
    tags: ['corrosion-free-lpg-cylinder', 'fiber-lpg-cylinders'],
    excerpt: 'Saltwater environments are brutal on steel cylinders. Composite fiber alternatives offer unmatched corrosion resistance and safety for marine and coastal use.',
  },
  {
    slug: 'why-more-families-choosing-waatechnologies-for-safer-lpg-storage-introduction-2',
    title: 'Why More Families Are Choosing WAATechnologies for Safer LPG Storage',
    date: 'Dec 5, 2024',
    category: 'WAATechCylinders',
    type: 'blog',
    tags: ['waatechnologies', 'safe-lpg-cylinders'],
    excerpt: 'Pakistani families are increasingly choosing WAA Technologies composite cylinders — discovering the peace of mind that comes with truly explosion-proof LPG storage.',
  },
  {
    slug: 'waa-technologies-leading-the-future-of-lpg-composite-cylinders-with-innovation-safety-and-sustainability-2',
    title: 'WAA Technologies: Leading the Future of LPG Composite Cylinders',
    date: 'Dec 1, 2024',
    category: 'WAATechCylinders',
    type: 'blog',
    tags: ['waatechnologies', 'composite-lpg-cylinders'],
    excerpt: 'How WAA Technologies is positioning Pakistan as a leader in composite LPG cylinder manufacturing through innovation, safety standards, and sustainable production.',
  },
  {
    slug: 'lpg-industry-trends-the-growing-demand-for-composite-cylinders',
    title: 'LPG Industry Trends: The Growing Demand for Composite Cylinders',
    date: 'Nov 25, 2024',
    category: 'WAATechCylinders',
    type: 'blog',
    tags: ['lpg-industry-trends', 'composite-lpg-cylinders'],
    excerpt: 'Market analysis of the global and Pakistani LPG industry\'s shift toward composite cylinders — driven by safety regulations, consumer preference, and cost economics.',
  },
  {
    slug: 'why-waa-techs-lpg-cylinders-are-a-game-changer-for-the-energy-industry',
    title: "Why WAA Tech's LPG Cylinders Are a Game-Changer for the Energy Industry",
    date: 'Nov 20, 2024',
    category: 'WAATechCylinders',
    type: 'blog',
    tags: ['energy-industry-innovation', 'composite-lpg-cylinders'],
    excerpt: "WAA Technologies' composite LPG cylinders are disrupting Pakistan's energy sector with technology that is safer, lighter, and more sustainable than anything that came before.",
  },
  {
    slug: 'top-5-features-that-make-waa-techs-composite-cylinders-stand-out',
    title: "Top 5 Features That Make WAA Tech's Composite Cylinders Stand Out",
    date: 'Nov 15, 2024',
    category: 'WAATechCylinders',
    type: 'blog',
    tags: ['lpg-cylinder-features', 'waa-tech-composite-cylinders'],
    excerpt: 'From explosion-proof design to translucent gas level visibility — the five standout features that separate WAA composite cylinders from every competitor.',
  },
  {
    slug: 'a-greener-choice-the-eco-friendly-features-of-waa-composite-cylinders-2',
    title: 'A Greener Choice: The Eco-Friendly Features of WAA Composite Cylinders',
    date: 'Nov 12, 2024',
    category: 'WAATechCylinders',
    type: 'blog',
    tags: ['eco-friendly-lpg-storage', 'waa-tech-composite-cylinders'],
    excerpt: 'WAA composite cylinders are not only safer than steel — they\'re also significantly greener. Discover the environmental design choices built into every WAA cylinder.',
  },
  {
    slug: '5-reasons-to-switch-to-composite-lpg-cylinders-for-your-home',
    title: '5 Reasons to Switch to Composite LPG Cylinders for Your Home',
    date: 'Nov 10, 2024',
    category: 'WAATechCylinders',
    type: 'blog',
    tags: ['household-lpg-solutions', 'composite-lpg-cylinders'],
    excerpt: 'Safety, weight, lifespan, visibility, and style — five compelling reasons why Pakistani homeowners are making the switch to composite LPG cylinders.',
  },
  {
    slug: 'best-practice-for-safely-using-lpg-composite-cylinders-at-home',
    title: 'Best Practice for Safely Using LPG Composite Cylinders at Home',
    date: 'Nov 8, 2024',
    category: 'WAATechCylinders',
    type: 'blog',
    tags: ['lpg-safety-practices', 'safe-lpg-usage', 'home-lpg-solutions'],
    excerpt: 'A practical guide for Pakistani households on safely storing, handling, and using composite LPG cylinders — maximizing safety and cylinder lifespan.',
  },
  {
    slug: 'the-role-of-recyclable-materials-in-the-lpg-fiber-cylinder-manufacturing',
    title: 'The Role of Recyclable Materials in LPG Fiber Cylinder Manufacturing',
    date: 'Nov 7, 2024',
    category: 'WAATechCylinders',
    type: 'blog',
    tags: ['recyclable-materials-in-lpg-cylinders', 'sustainable-gas-cylinder-manufacturing'],
    excerpt: 'How HDPE liners and glass fibre components make composite LPG cylinders one of the most recyclable gas storage solutions on the market.',
  },
  {
    slug: 'blast-proof-technology-works-in-lpg-cylinders',
    title: 'Blast-Proof Technology: How It Works in LPG Cylinders',
    date: 'Nov 6, 2024',
    category: 'WAATechCylinders',
    type: 'blog',
    tags: ['blast-proof-technology', 'how-blast-proof-technology-works', 'blast-proof-lpg-cylinders'],
    excerpt: 'A technical explanation of how composite winding technology achieves true blast-proof performance — and why it is fundamentally different from steel cylinder safety claims.',
  },
  {
    slug: 'benefits-of-blast-proof-lpg-cylinders-household-safety',
    title: 'Benefits of Blast-Proof LPG Cylinders for Household Safety',
    date: 'Nov 6, 2024',
    category: 'WAATechCylinders',
    type: 'blog',
    tags: ['blast-proof-lpg-cylinders', 'household-safety', 'lpg-cylinder-for-home'],
    excerpt: 'How blast-proof composite LPG cylinders are reducing kitchen accidents, fire incidents, and injuries in Pakistani homes.',
  },
  {
    slug: 'benefits-of-blast-proof-lpg-cylinders',
    title: 'Benefits of Blast-Proof LPG Cylinders',
    date: 'Nov 5, 2024',
    category: 'WAATechCylinders',
    type: 'blog',
    tags: ['blast-proof-lpg-cylinder', 'blast-proof-technology'],
    excerpt: 'An overview of the wide-ranging benefits of blast-proof composite LPG cylinders for homes, businesses, and communities across Pakistan.',
  },
  {
    slug: 'recyclable-materials-in-lpg-fiber-cylinder-manufacturing',
    title: 'Recyclable Materials in LPG Fiber Cylinder Manufacturing',
    date: 'Nov 4, 2024',
    category: 'WAATechCylinders',
    type: 'blog',
    tags: ['recyclable-lpg-fiber-cylinders', 'sustainable-energy-solutions'],
    excerpt: 'The role of recyclable HDPE and fiberglass materials in making composite LPG cylinder manufacturing more sustainable and circular.',
  },
  {
    slug: 'best-practices-for-safely-using-lpg-composite-cylinders',
    title: 'Best Practices for Safely Using LPG Composite Cylinders',
    date: 'Nov 3, 2024',
    category: 'WAATechCylinders',
    type: 'blog',
    tags: ['lpg-safety-practices', 'safe-handling-of-lpg', 'lpg-maintenance-guidelines'],
    excerpt: 'Essential safety guidelines for storing, transporting, connecting, and using composite LPG cylinders safely in any environment.',
  },
  {
    slug: '5-reasons-to-switch-to-composite-lpg-cylinder',
    title: '5 Reasons to Switch to a Composite LPG Cylinder',
    date: 'Nov 2, 2024',
    category: 'WAATechCylinders',
    type: 'blog',
    tags: ['composite-lpg-cylinders', 'household-lpg-solutions'],
    excerpt: 'Still using a steel LPG cylinder? Here are five practical reasons why upgrading to a composite alternative is the smarter choice.',
  },
  {
    slug: 'the-eco-friendly-features-of-waa-composite-cylinders',
    title: 'The Eco-Friendly Features of WAA Composite Cylinders',
    date: 'Nov 1, 2024',
    category: 'WAATechCylinders',
    type: 'blog',
    tags: ['eco-friendly-lpg-storage', 'waa-tech-lpg-cylinders'],
    excerpt: 'A deep dive into the sustainable design and material choices that make WAA composite cylinders one of the most eco-friendly LPG products in Pakistan.',
  },
  {
    slug: 'features-waatech-composite-cylinders-standout',
    title: 'Features That Make WAATech Composite Cylinders Stand Out',
    date: 'Oct 28, 2024',
    category: 'WAATechCylinders',
    type: 'blog',
    tags: ['waa-tech-composite-cylinders', 'lpg-cylinder-features'],
    excerpt: 'What separates WAATech composite cylinders from the competition? A feature-by-feature breakdown of the technology and standards behind every WAA product.',
  },
  {
    slug: 'lpg-cylinders-game-changer-energy-industry',
    title: 'LPG Cylinders: A Game-Changer for the Energy Industry',
    date: 'Oct 25, 2024',
    category: 'WAATechCylinders',
    type: 'blog',
    tags: ['energy-industry-advancements', 'composite-lpg-cylinders'],
    excerpt: 'How composite LPG cylinders are transforming the energy industry — from improved safety standards to new distribution models and sustainable manufacturing.',
  },
  {
    slug: 'lpg-industry-trends-growing-demand-for-composite-cylinders',
    title: 'LPG Industry Trends: Growing Demand for Composite Cylinders',
    date: 'Oct 22, 2024',
    category: 'WAATechCylinders',
    type: 'blog',
    tags: ['lpg-industry-trends', 'composite-lpg-cylinders'],
    excerpt: 'Industry data and market trends showing accelerating adoption of composite LPG cylinders across Pakistan and globally.',
  },
  {
    slug: 'waa-technologies-leading-the-future-of-lpg-composite-cylinders-with-innovation-safety-and-sustainability',
    title: 'WAA Technologies: Leading the Future of LPG Composite Cylinders with Innovation, Safety and Sustainability',
    date: 'Oct 18, 2024',
    category: 'WAATechCylinders',
    type: 'blog',
    tags: ['waatechnologies', 'composite-lpg-cylinders', 'sustainable-lpg-solutions'],
    excerpt: 'How WAA Technologies is spearheading Pakistan\'s composite cylinder revolution through relentless innovation, uncompromising safety standards, and sustainable manufacturing.',
  },
  {
    slug: 'a-greener-choice-the-eco-friendly-features-of-waa-composite-cylinders',
    title: 'A Greener Choice: Eco-Friendly Features of WAA Composite Cylinders',
    date: 'Oct 15, 2024',
    category: 'WAATechCylinders',
    type: 'blog',
    tags: ['eco-friendly-lpg-storage', 'waa-tech-composite-cylinders', 'green-energy-solutions'],
    excerpt: 'How WAA composite cylinders\' eco-friendly material choices, manufacturing processes, and longevity deliver a genuinely greener LPG solution.',
  },
  {
    slug: 'why-more-families-choosing-waatechnologies-for-safer-lpg-storage-introduction',
    title: 'Why More Families Are Choosing WAATechnologies for Safer LPG Storage',
    date: 'Oct 10, 2024',
    category: 'WAATechCylinders',
    type: 'blog',
    tags: ['waatechnologies', 'safe-lpg-cylinders', 'household-lpg-cylinder'],
    excerpt: 'Across Pakistan, more families are discovering the life-changing safety benefits of WAA Technologies composite LPG cylinders. Here\'s why.',
  },

  // ── CASE STUDIES ─────────────────────────────────────────────────────────────
  {
    slug: 'waatechnologies-corrosion-resistant-cylinder-coastal-warehouse',
    title: 'WAATechnologies Prevents Corrosion-Related Incidents in a Coastal Warehouse',
    date: 'Nov 6, 2024',
    category: 'casestudies',
    type: 'case-study',
    location: 'Karachi',
    tags: ['coastal-warehouse-safety', 'corrosion-resistant-lpg-cylinder', 'karachi'],
    excerpt: 'A Karachi warehouse storing LPG experienced multiple incidents with rusted steel cylinders. After switching to WAA composite cylinders, zero corrosion-related incidents occurred over 12 months.',
  },
  {
    slug: 'waatechnologies-blast-proof-cylinder-outdoor-camping-safety',
    title: "Safe Cooking for Remote Campsites: WAATechnologies' Cylinder Ensures a Secure Adventure",
    date: 'Nov 6, 2024',
    category: 'casestudies',
    type: 'case-study',
    location: 'Thar Desert',
    tags: ['blast-proof-cylinder', 'outdoor-festival-safety'],
    excerpt: 'Outdoor adventurers in the Thar Desert needed LPG cylinders that could withstand extreme temperatures, UV exposure, and rough handling. WAA composite cylinders proved ideal.',
  },
  {
    slug: 'waatechnologies-blast-proof-cylinders-busy-restaurant-safety',
    title: "Protecting Business Owners: WAATechnologies' Solution in a Busy Restaurant Environment",
    date: 'Nov 6, 2024',
    category: 'casestudies',
    type: 'case-study',
    location: 'Islamabad',
    tags: ['blast-proof-cylinder', 'commercial-kitchen-safety', 'islamabad', 'restaurant-safety'],
    excerpt: "An Islamabad restaurant with high daily LPG usage was worried about the fire risk of steel cylinders in a busy kitchen. WAA's non-blast composite cylinders provided complete peace of mind.",
  },
  {
    slug: 'preventing-tragedy-waatechnologies-blast-proof-cylinder-lahore',
    title: "Preventing Tragedy in a Residential Area: How WAATechnologies' Blast-Proof Cylinder Avoided a Catastrophe",
    date: 'Nov 6, 2024',
    category: 'casestudies',
    type: 'case-study',
    location: 'Lahore',
    tags: ['blast-proof-lpg-cylinder', 'residential-safety', 'lahore', 'gas-leak-prevention'],
    excerpt: "In a dense residential neighbourhood in Lahore, a kitchen fire tested WAA's cylinder under real-world conditions. The composite cylinder did not explode — confirming the non-blast design.",
  },
  {
    slug: 'waatechnologies-blast-proof-cylinder-public-event-safety',
    title: 'WAATechnologies Ensures Safety at a High-Footfall Public Event',
    date: 'Nov 6, 2024',
    category: 'casestudies',
    type: 'case-study',
    location: 'Peshawar',
    tags: ['public-event-safety', 'high-footfall-safety', 'peshawar', 'blast-proof-cylinder'],
    excerpt: 'A public food festival in Peshawar required LPG cylinders certified for high-footfall environments. WAA composite cylinders met the strict safety requirements and performed flawlessly.',
  },
  {
    slug: 'camping-blast-proof-lpg-cylinders-outdoor-adventures',
    title: 'Blast-Proof LPG Cylinders for Outdoor Adventures and Camping',
    date: 'Oct 28, 2024',
    category: 'casestudies',
    type: 'case-study',
    location: 'Pakistan',
    tags: ['blast-proof-lpg-cylinders', 'outdoor-festival-safety'],
    excerpt: 'How WAA composite cylinders have become the go-to choice for campers, trekkers, and outdoor enthusiasts across Pakistan seeking safe, lightweight gas storage.',
  },
];

export function getPostBySlug(slug: string): Post | undefined {
  return allPosts.find((p) => p.slug === slug);
}

export function getBlogPosts(): Post[] {
  return allPosts.filter((p) => p.type === 'blog');
}

export function getCaseStudies(): Post[] {
  return allPosts.filter((p) => p.type === 'case-study');
}
